language: go

go:
  - "1.11.x"
  - "1.12.x"

node_js:
  - "8"

env:
  - GO111MODULE=on

install:
  - CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build app/main.go
  - cd ui
  - npm install
  - npm run build