language: go

node_js:
  - "8"

services:
  - docker

go:
  - "1.11.x"
  - "1.12.x"

env:
  - GO111MODULE=on

install:
  - go build app/main.go
  - cd ui
  - npm install
  - npm run build
  - cd ..
  - docker build --pull -t "yupaits/go-pi-monitor" .

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master