language: go

services:
  - docker

go:
  - "1.11.x"
  - "1.12.x"

env:
  - GO111MODULE=on

install:
  - go build app/main.go
  - docker build -pull -t "yupaits/go-pi-monitor" .

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master